// <auto-generated />
namespace ProduitApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changementscalprixunitaire : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changementscalprixunitaire));
        
        string IMigrationMetadata.Id
        {
            get { return "201804251500000_changement scal prix unitaire"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
